# === MAIN MODULE / EXECUTION FUNCTION ===
import time

if __name__ == "__main__":

    # START CLOCK TO RECORD SPEED OF PROGRAM

    # ORCHESTRATE PYRAMID BLENDING

    # CALL GUI TO GENERATE MASK

    # REPORT TIME OF PROGRAM
